services:
  # PocketBase backend service
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile.prod
    container_name: pocketbase-prod
    restart: unless-stopped
    command: ["serve", "--http=0.0.0.0:8091"]
    ports:
      - "8091:8091"
    volumes:
      - pb_data_prod:/pb_data
    environment:
      - POCKETBASE_ENV=production
      - EXTERNAL_PORT=8091
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8091/_/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  # SvelteKit frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - pocketbase
    environment:
      - VITE_POCKETBASE_URL=http://localhost:8091
    networks:
      - app-network

# Named volume for PocketBase data persistence
volumes:
  pb_data_prod:
    driver: local

# Network for service communication
networks:
  app-network:
    driver: bridge
