services:
  # PocketBase backend service
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    container_name: pocketbase
    restart: unless-stopped
    command: ["serve", "--http=0.0.0.0:8090"]
    ports:
      - "8091:8090"
    volumes:
      # Persistent volume for database and files
      # WARNING: Use 'docker compose down' to stop without losing data
      # Use 'docker compose down -v' to remove data (clean slate)
      - pb_data:/pb_data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/_/"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - app-network

  # SvelteKit frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      # Bind mount source code for hot reload
      - ./frontend:/app
      # Anonymous volumes to preserve container's node_modules and build cache
      - /app/node_modules
      - /app/.svelte-kit
    environment:
      # PocketBase URL for browser (via host machine)
      - VITE_POCKETBASE_URL=${VITE_POCKETBASE_URL:-http://localhost:8090}
      # Internal URL for server-side calls (if needed)
      - INTERNAL_POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      - pocketbase
    networks:
      - app-network

# Named volume for PocketBase data persistence
volumes:
  pb_data:
    driver: local

# Network for service communication
networks:
  app-network:
    driver: bridge
